services:
  web: 
    build:
      context: app
      target: builder
    volumes:
      - ${WORKING_DIR}/app:/app
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
    ports: 
      - '9001:8000'
